version: "3.6"
services:
  app:
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=80
      - IS_DEBUG=true
    build: .
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/opt/app:cached

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: