"""empty message

Revision ID: 0d76f61af75d
Revises: 1fc15111b842
Create Date: 2021-11-04 09:06:38.209700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d76f61af75d'
down_revision = '1fc15111b842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_payments', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_jobs_id', table_name='jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    op.drop_column('job_payments', 'id')
    # ### end Alembic commands ###
