"""empty message

Revision ID: 0ecb02d3f49f
Revises: eb08026324a7
Create Date: 2021-11-03 16:53:54.509962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecb02d3f49f'
down_revision = 'eb08026324a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_payments',
    sa.Column('stripe_product_id', sa.String(length=256), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_payments')
    # ### end Alembic commands ###
