"""empty message

Revision ID: 1fc15111b842
Revises: 0ecb02d3f49f
Create Date: 2021-11-03 17:45:39.120914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc15111b842'
down_revision = '0ecb02d3f49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_payments', sa.Column('payment_id', sa.String(length=256), nullable=False))
    op.drop_column('job_payments', 'stripe_product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_payments', sa.Column('stripe_product_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('job_payments', 'payment_id')
    # ### end Alembic commands ###
