"""empty message

Revision ID: 4752e21efae6
Revises: fea2d1483cc3
Create Date: 2021-11-05 09:11:20.891639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4752e21efae6'
down_revision = 'fea2d1483cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE jobs SET posted_at = NOW();")
    op.alter_column('jobs', 'posted_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'posted_at')
    # ### end Alembic commands ###
