"""empty message

Revision ID: 742feaa886e4
Revises: bc52461982ab
Create Date: 2021-11-03 13:56:05.049735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742feaa886e4'
down_revision = 'bc52461982ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_unique_id', table_name='jobs')
    op.drop_column('jobs', 'unique_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('unique_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_index('ix_jobs_unique_id', 'jobs', ['unique_id'], unique=False)
    # ### end Alembic commands ###
