"""empty message

Revision ID: b0484c1e8c11
Revises: 0d76f61af75d
Create Date: 2021-11-04 09:13:19.505998

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b0484c1e8c11'
down_revision = '0d76f61af75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table job_payments drop id')
    op.execute('alter table job_payments add id serial primary key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
