"""empty message

Revision ID: eb08026324a7
Revises: 
Create Date: 2021-11-03 16:47:44.657820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb08026324a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email_address', sa.Unicode(length=256), nullable=False),
    sa.Column('type', sa.Enum('EMPLOYER', 'CANDIDATE', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email_address'), 'users', ['email_address'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('title', sa.Unicode(length=256), nullable=False),
    sa.Column('location', sa.Unicode(length=64), nullable=False),
    sa.Column('job_description', sa.Unicode(length=5000), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=False),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency_code', sa.String(length=3), nullable=False),
    sa.Column('interview_rounds', sa.Integer(), nullable=False),
    sa.Column('interview_description', sa.String(length=1000), nullable=True),
    sa.Column('benefits', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'AWAITING_PAYMENT', 'PAYMENT_EXPIRED', name='jobstatus'), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('stripe_users',
    sa.Column('stripe_customer_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_users')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email_address'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
